services:
    mongo:
        image: mongo:7
        container_name: mongodev
        ports:
            - "27017:27017"
        environment:
            MONGO_INIT_DATABASE: maisprati-hub
            MONGO_INIT_ROOT_USERNAME: admin
            MONGO_INIT_ROOT_PASSWORD: admin123
        volumes:
            - mongo_data:/data/db
        restart: unless-stopped

volumes:
    mongo_data:
